// class Sinistre {
//   constructor(
//     id,
//     AdresseASB,
//     AdresseCB,
//     ArriereA,
//     ArriereB,
//     AvantA,
//     AvantB,
//     CirconstanceCB,
//     Code_PostalASB,
//     DescriptionCB,
//     DroitA,
//     DroitB,
//     DetailleCB,
//     EmailASB,
//     GaucheA,
//     GaucheB,
//     HautA,
//     HautB,
//     Localisation,
//     MarqueB,
//     NomASB,
//     NomB,
//     NomCB,
//     Numero_immatriculationB,
//     Pays_immatriculationB,
//     PrenomASB,
//     PrenomCB,
//     SignatureA,
//     SignatureB,
//     TelephoneASSB,
//     adresseB,
//     agenceB,
//     assure,
//     auB,
//     blesse,
//     categorieCB,
//     circonstance,
//     conducteur,
//     cote_droit,
//     cote_gauche,
//     date_naissanceCB,
//     duB,
//     emailB,
//     emailCB,
//     fin_valide_permisCB,
//     nom_agenceB,
//     num_carte_verteB,
//     num_contratB,
//     num_permisCB,
//     observation,
//     paysB,
//     paysCB,
//     prise_enchargeB,
//     sinistre,
//     telephoneAB,
//     telephoneCB,
//     temoins,
//     vehicule
//   ){
//     this.id = id;
//     this.AdresseASB = AdresseASB;
//     this.AdresseCB = AdresseCB,
//     this.ArriereA = ArriereA,
//     this.ArriereB = ArriereB,
//     this.AvantA = AvantA,
//     this.AvantB = AvantB,
//     this.CirconstanceCB = CirconstanceCB,
//     this.Code_PostalASB = Code_PostalASB,
//     this.DescriptionCB = DescriptionCB,
//     this.DroitA = DroitA,
//     this.DroitB = DroitB,
//     this.DetailleCB = DetailleCB,
//     this.EmailASB = EmailASB,
//     this.GaucheA = GaucheA,
//     this.GaucheB = GaucheB,
//     this.HautA = HautA,
//     this.HautB = HautB,
//     this.Localisation = Localisation,
//     this.MarqueB = MarqueB,
//     this.NomASB = NomASB,
//     this.NomB = NomB,
//     this.NomCB = NomCB,
//     this.Numero_immatriculationB = Numero_immatriculationB,
//     this.Pays_immatriculationB = Pays_immatriculationB,
//     this.PrenomASB = PrenomASB,
//     this.PrenomCB = PrenomCB,
//     this.SignatureA = SignatureA,
//     this.SignatureB = SignatureB,
//     this.TelephoneASSB = TelephoneASSB,
//     this.adresseB = adresseB,
//     this.agenceB = agenceB,
//     this.assure = assure,
//     this.auB = auB,
//     this.blesse = blesse,
//     this.categorieCB = categorieCB,
//     this.circonstance = circonstance,
//     this.conducteur = conducteur,
//     this.cote_droit = cote_droit,
//     this.cote_gauche = cote_gauche,
//     this.date_naissanceCB = date_naissanceCB,
//     this.duB = duB,
//     this.emailB = emailB,
//     this.emailCB = emailCB,
//     this.fin_valide_permisCB = fin_valide_permisCB,
//     this.nom_agenceB = nom_agenceB,
//     this.num_carte_verteB = num_carte_verteB,
//     this.num_contratB = num_contratB,
//     this.num_permisCB = num_permisCB,
//     this.observation = observation,
//     this.paysB = paysB,
//     this.paysCB = paysCB,
//     this.prise_enchargeB = prise_enchargeB,
//     this.sinistre = sinistre,
//     this.telephoneAB = telephoneAB,
//     this.telephoneCB = telephoneCB,
//     this.temoins = temoins,
//     this.vehicule = vehicule
//   }
// }


class Sinistre {
  constructor(
        id,
        ArriereA,
        ArriereB,
        AvantA,
        AvantB,
        DroitA,
        DroitB,
        GaucheA,
        GaucheB,
        HautA,
        HautB,
        Localisation,
        SignatureA,
        SignatureB,
        assure,
        assureB,
        blesse,
        circonstance,
        conducteur,
        conducteurB,
        observation,
        sinistre,
        temoins,
        vehicule,
        vehiculeB,
        assuranceA,
        assuranceB
  ){
    this.id = id,
    this.ArriereA = ArriereA,
    this.ArriereB = ArriereB,
    this.AvantA = AvantA,
    this.AvantB = AvantB,
    this.DroitA = DroitA,
    this.DroitB = DroitB,
    this.GaucheA = GaucheA,
    this.GaucheB = GaucheB,
    this.HautA = HautA,
    this.HautB = HautB,
    this.Localisation = Localisation,
    this.SignatureA = SignatureA,
    this.SignatureB = SignatureB,
    this.assure = assure,
    this.assureB = assureB,
    this.blesse = blesse,
    this.circonstance = circonstance,
    this.conducteur = conducteur,
    this.conducteurB = conducteurB,
    this.observation = observation,
    this.sinistre = sinistre,
    this.temoins = temoins,
    this.vehicule = vehicule,
    this.vehiculeB = vehiculeB,
    this.assuranceA = assuranceA,
    this.assuranceB = assuranceB
  }
}
module.exports= Sinistre;